apiVersion: v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
    template:
      metadata:
        labels:
          app: flaskapi
      spec:
        containers:
        - name: flaskapi
          image: flask-api
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
          env:
          - name: db_root_password
            valueFrom:
              secretKeyRef:
                name: flaskapi-secret
                key: db_root_password
          - name: db_name
            value: flaskapi


---
apiVersion: v1
kind: "Service"
metadata:
  name: flask-service
spec:
  selector:
    app: flaskapi
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
